apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-environments
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - env: dev
            namespace: dev
            valueFile: values-dev.yaml
            autoSync: true
          - env: prod
            namespace: prod
            valueFile: values-prod.yaml
            autoSync: false
  template:
    metadata:
      name: 'myapp-{{ .env }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/setterwars/DevOps-Core-Course.git
        targetRevision: lab13
        path: k8s/myapp
        helm:
          valueFiles:
            - values.yaml
            - '{{ .valueFile }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    {{- if .autoSync }}
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
    {{- end }}
