replicaCount: 2

nameOverride: ""
fullnameOverride: ""

image:
  repository: zsalavat/devops-info-service-python
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  portName: http
  port: 80
  targetPort: 5000
  nodePort: 30083

serviceAccount:
  create: true
  name: ""
  annotations: {}

podAnnotations: {}

config:
  appName: devops-info-service
  environment: dev
  logLevel: INFO
  mountPath: /config

secret:
  username: "dev-user"
  password: "dev-pass"

persistence:
  enabled: true
  mountPath: /data
  fileName: visits
  accessMode: ReadWriteOnce
  size: 100Mi
  storageClass: ""

bootstrap:
  enabled: false
  mountPath: /bootstrap
  downloadUrl: https://example.com
  fileName: index.html
  waitForService: kubernetes.default.svc.cluster.local

serviceMonitor:
  enabled: false
  namespace: ""
  interval: 15s
  scrapeTimeout: 10s
  path: /metrics
  labels:
    release: monitoring

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"

vault:
  enabled: false
  role: myapp
  secretPath: secret/data/myapp/config

statefulset:
  enabled: false
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0

rollout:
  enabled: false
  strategy: canary
  revisionHistoryLimit: 2
  canary:
    maxSurge: 1
    maxUnavailable: 0
  blueGreen:
    autoPromotionEnabled: false
    scaleDownDelaySeconds: 30
    previewServiceType: ClusterIP
  analysis:
    enabled: false
    interval: 10s
    count: 3
    failureLimit: 1
